name: Daily Repo Monitor
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:  
  contents: write
  issues: write
  pull-requests: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run monitoring script
        run: python your_script.py

      - name: Commit updates
        if: success()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "Auto-update monitoring data" || echo "No changes"
          git push
